name: Linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]   
jobs:
  check-bats-version:
    runs-on: [ubuntu-latest, windows-latest]
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod  
      - name: linting styles
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit     

